# docker-compose.yml (development)
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./project-helios-firebase-service-account.json:/run/secrets/project-helios-firebase-service-account.json:ro
