"""create initial tables

Revision ID: 91fab2daf0d6
Revises: 
Create Date: 2026-03-14 20:42:47.418280+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '91fab2daf0d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('daily_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories_actual', sa.Integer(), nullable=True),
    sa.Column('protein_actual', sa.Integer(), nullable=True),
    sa.Column('sleep_actual', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('workout_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_period_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('calorie_target_snapshot', sa.Integer(), nullable=False),
    sa.Column('protein_target_snapshot', sa.Integer(), nullable=False),
    sa.Column('sleep_target_snapshot', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.CheckConstraint('calorie_target_snapshot >= 0', name='ck_log_cal_snapshot_non_negative'),
    sa.CheckConstraint('calories_actual >= 0', name='ck_log_calories_non_negative'),
    sa.CheckConstraint('protein_actual >= 0', name='ck_log_protein_non_negative'),
    sa.CheckConstraint('protein_target_snapshot >= 0', name='ck_log_prot_snapshot_non_negative'),
    sa.CheckConstraint('sleep_actual >= 0', name='ck_log_sleep_non_negative'),
    sa.CheckConstraint('sleep_target_snapshot >= 0', name='ck_log_sleep_snapshot_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_logs_user_date')
    )
    op.create_table('target_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=False),
    sa.Column('protein_target', sa.Integer(), nullable=False),
    sa.Column('sleep_target', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.CheckConstraint('calorie_target >= 0', name='ck_target_calories_non_negative'),
    sa.CheckConstraint('protein_target >= 0', name='ck_target_protein_non_negative'),
    sa.CheckConstraint('sleep_target >= 0', name='ck_target_sleep_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_configs')
    op.drop_table('daily_logs')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
